### ISSUE TITLE
Using the plugin gives 401 on profile querying for customer /store/auth

### ISSUE THREAD

**Issue by edihasaj** [adrien2p/medusa-plugins#22] opened 2022-11-16 18:42 UTC
The login / signup workflow works like a charm, great job for you on this 😁👌. But I don't get it why it returns 401 after I successfully login/signup with e.x. Google, the cookies are being with the request but I just get 401. If I disable the plugin everything works as expected.

this is for medusa-plugin-auth

**Comment by adrien2p** [comment] 2022-11-16 20:10
Thanks a lot for the kind word 😍 would it be caused by the redirect that you fixed in the last pr?

**Comment by adrien2p** [comment] 2022-11-16 20:14
Actually, just saw that I assign the customer.id to id instead of customer_id i ll fix it unless you do it before me 😅

**Comment by adrien2p** [comment] 2022-11-16 21:07
I think that this should fix your issue https://github.com/adrien2p/medusa-plugins/pull/24

**Comment by adrien2p** [comment] 2022-11-16 21:11
https://github.com/adrien2p/medusa-plugins/releases/tag/medusa-plugin-auth%400.3.1

**Closed by adrien2p** 2022-11-16 21:11 UTC

**Comment by edihasaj** [comment] 2022-11-16 21:23
Thanks a lot, I'll try and let u know 🙌🥳

**Comment by edihasaj** [comment] 2022-11-16 22:10
@adrien2p nope, I still get the same error, I'll dig deeper to see if I can find something wrong

**Comment by edihasaj** [comment] 2022-11-16 23:52
I am debugging, changing some more id to customer_id in done callback, touching this cookie configs but still nothing. It is very wierd that if I try to login normally it works, but with google for exmple it doesn't.. Am I missing something? Should I send access token in headers not let it to go with cookies as it goes?
