### ISSUE TITLE
Google OAuth login not working for admin 

### ISSUE THREAD

**Issue by nhatanhit** [adrien2p/medusa-plugins#87] opened 2023-06-30 16:18 UTC
Hello, I am using plugin medusa-plugin-auth for Google OAuth login on admin site (localhost:7000) . My localhost for backend is : localhost:9000 

Below are configurations that I have done on my Google Developer Console
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/4cf32cbb-b41f-4aae-8635-bd2101945397)
My admin configurations for the plugin is as following 
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/a100fb6d-6423-43ee-8801-e6b11dc0657b)

When I click onto the button Login By Google , it redirects me to this screen
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/df5fd223-aafb-4ff0-89e8-3af50593b5dc)

Can you please let me know which step I am missing ? 
Thanks

**Comment by adrien2p** [comment] 2023-07-02 21:43
Do you have any places in your backend where you would have applied the authenticate middleware to /admin?

**Comment by nhatanhit** [comment] 2023-07-04 04:36
Hi @adrien2p 
Yes, I applied the middleware for some /admin sub paths, but not for entire admin paths

**Comment by adrien2p** [comment] 2023-07-04 10:35
Sounds strange, I feel like the unauthorised comes from the authenticate middleware, cause you get than once you call the end point. Would you have a small repo to reproduce it that i can test? It does not have to include all your project, just the simpliest repo to reproduce this behaviour

**Comment by odhekar** [comment] 2023-07-04 10:54
I am facing the same issue and it seems the strategyNames returns blank for key "google". This is what I get in my setup,
```json
{
  "auth0": { "admin": "auth0.admin.medusa-auth-plugin", "store": "auth0.store.medusa-auth-plugin" },
  "facebook": { "admin": "facebook.admin.medusa-auth-plugin", "store": "facebook.store.medusa-auth-plugin" },
  "google": {},
  "linkedin": { "admin": "linkedin.admin.medusa-auth-plugin", "store": "linkedin.store.medusa-auth-plugin" },
  "firebase": { "admin": "firebase.admin.medusa-auth-plugin", "store": "firebase.store.medusa-auth-plugin" },
  "azure_oidc": { "admin": "azure-oidc.admin.medusa-auth-plugin", "store": "azure-oidc.store.medusa-auth-plugin" }
}
```

**Comment by adrien2p** [comment] 2023-07-05 07:04
@odhekar thanks for that info, where did you get that?

**Comment by odhekar** [comment] 2023-07-05 10:20
I added some logging in `node_modules/medusa-plugin-auth/core/validate-callback.js` when I couldn't repro the problem with my custom callback (that still didn't work until I realized that the callback has to return user.id).
This particular check in validate-callback.js fails because the google key is blank,

```js
if ((strict === 'all' || strict === 'admin') &&
      (!user.metadata || user.metadata[types_1.AUTH_PROVIDER_KEY] !== types_1.strategyNames[strategyErrorIdentifier].admin)) {
      throw new medusa_core_utils_1.MedusaError(medusa_core_utils_1.MedusaError.Types.INVALID_DATA, `Admin with email ${email} already exists`);
    }
```

I have just started evaluating medusa and therefore, this is pretty much fresh backend + admin install with a Google login widget on the login screen.
```json
  "dependencies": {
    "@medusajs/admin": "^7.0.0-beta-20230624084632",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.4",
    "@medusajs/event-bus-redis": "^1.8.7",
    "@medusajs/file-local": "^1.0.1",
    "@medusajs/medusa": "^1.12.2-beta-20230624084632",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "^16.1.4",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^6.0.0",
    "medusa-plugin-auth": "^1.5.1",
    "typeorm": "^0.3.16"
  },
```

**Comment by odhekar** [comment] 2023-07-05 10:24
One thing I would add here - I wish the documentation on this plugin is a bit more descriptive. It's not obvious what are the basic steps needed to use only the social login. I want to use just Google and facebook but the plugin documentation skips the need to have authProvider in metadata and how admin users should be provisioned on a fresh install etc.  
Just my two cents, this is a great product and I wish the documentation was easier.

**Comment by odhekar** [comment] 2023-07-05 19:08
@adrien2p just checked and the validate-callback.js works fine for facebook in admin but fails for google.

**Comment by adrien2p** [comment] 2023-07-05 20:23
@odhekar indeed, in order for an admin to use the social login, the authProvider needs to be set in order to prevent anybody from being able to authenticate to your admin and to get an account created for security reason. Also, this part is explain at the end of each provider description in the doc. Maybe, would you like to create a pr to improve the part you think are lacking explanation ? ☺️

**Comment by adrien2p** [comment] 2023-07-05 20:26
The fails is still due to the constraints you have shown above or did you solve it by adding the authProvider?

**Comment by odhekar** [comment] 2023-07-06 01:23
@adrien2p The "why" is clear but the problem is "how" 😉. The provider description in the documentation assumes somebody new (such as me) knows about "authProvider" in metadata and what it is supposed to contain i.e. familiarity with plugin codebase is assumed. I will see if I can do a PR in the doc on this.  
It was also not clear to me that the medusa db still remains the main user store (hope this is correct?).

Here is what I did,

1. OOTB medusa backend + admin
2. Added auth-plugin with Google config
3. Created a widget to add a login with Google button on the login page
4. Created a user using medusa cli with but without password.
   ```bash
   medusa user -e <username>@gmail.com
   ```
5. Updated the metadata column in in the user table to
   ```json
   {"authProvider":"google.admin.medusa-auth-plugin"}
   ``` 
6. Got the "Admin with email <username>@gmail.com already exists" error when I tried to login
7. I then added some logging as described [here](https://github.com/adrien2p/medusa-plugins/issues/87#issuecomment-1621468451) and realized the problem mentioned [here](https://github.com/adrien2p/medusa-plugins/issues/87#issuecomment-1620023018).
8. I then wrote a custom callback with checks for "strict" removed (didn't look like "strict" is available in the callback) and then finally login worked!
9. Repeated this for adding facebook login and that works without any custom callback.
10. In summary - there is some bug that causes the problem in step# 7

In between 6 & 7 I also tried custom callback but the documentation doesn't mention it is supposed to return user.id and I wasn't sure what the callback is supposed to do!

**Comment by adrien2p** [comment] 2023-07-06 05:28
Indeed i assumed that people would look at the typings I suppose, maybe as part of the doc we can also add the js types import special comment above the custom callback prop wdyt?

The thing i don't get is how do you get the strategyNames to be empty for google. They are declared here https://github.com/adrien2p/medusa-plugins/blob/main/packages/medusa-plugin-auth/src/types/index.ts line 60 and unless they are re assigned somewhere i don't see how it is possible

**Comment by adrien2p** [comment] 2023-07-06 07:05
When I try to reproduce the missing strategy name I don't succeed. It seems really weird that this key is missing since it is a const populated in the types and never reassigned

<img width="1872" alt="Screenshot 2023-07-06 at 09 03 13" src="https://github.com/adrien2p/medusa-plugins/assets/25098370/f54a82da-e472-4ae7-8996-100ca15a3c44">

**Comment by odhekar** [comment] 2023-07-06 10:42
> When I try to reproduce the missing strategy name I don't succeed. It seems really weird that this key is missing since it is a const populated in the types and never reassigned
> 
> <img alt="Screenshot 2023-07-06 at 09 03 13" width="1872" src="https://user-images.githubusercontent.com/25098370/251370768-f54a82da-e472-4ae7-8996-100ca15a3c44.png">

which build was this? I tried with a fresh install using stable builds (so no admin widgets) and still got this,

![image](https://github.com/adrien2p/medusa-plugins/assets/34801801/a79b9db4-6ad5-408a-ade7-3aa0b39f0f80)

`packages.json`
```json
"dependencies": {
    "@medusajs/admin": "^6.0.1",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.4",
    "@medusajs/event-bus-redis": "^1.8.7",
    "@medusajs/file-local": "^1.0.1",
    "@medusajs/medusa": "^1.12.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "^16.1.4",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^6.0.0",
    "medusa-plugin-auth": "^1.5.1",
    "typeorm": "^0.3.16"
  }
```

medusa-config.json
```json
  {
    resolve: "medusa-plugin-auth",
    options: {
      google: {
        clientID: "client id",
        clientSecret: "secret",
        admin: {
          callbackUrl: `${BACKEND_URL}/admin/auth/google/cb`,
          failureRedirect: `${ADMIN_URL}/login`,

          // The success redirect can be overriden from the client by adding a query param `?redirectTo=your_url` to the auth url
          // This query param will have the priority over this configuration
          successRedirect: `${ADMIN_URL}/app`,
        },
      },
    },
  },
```

**Comment by nhatanhit** [comment] 2023-07-06 16:58
Hi @adrien2p 
Please checkout this one :  https://github.com/nhatanhit/fresh-medusa/tree/master/src  , it's my small fresh medusa repo and it's initialized by running command 
`npx create-medusa-app`

**Comment by nhatanhit** [comment] 2023-07-09 10:30
Another update 
I tried debugging, the cors settings already applied for the path `/admin/auth/google`  with domain 
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/6f767f7f-84b8-4cfe-b4f3-bf31bc586d01)
But it still displays "Unauthorized" 
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/27b657e6-99e0-4797-8fbd-2f83acb7a3dd)

Tried putting the breakpoint on line 38 , but it's not reach when visiting the URL `http://localhost:9000/admin/auth/google` 
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/90447b0c-30a4-4fd3-9b06-f78598ddb46c)

**Comment by adrien2p** [comment] 2023-07-09 14:52
@nhatanhit this is not a cors issue since you receive unauthorised. Can you put a bp in the validate callback as you might have the same issue as de discussed with @odhekar

**Comment by nhatanhit** [comment] 2023-07-09 16:12
@adrien2p 
I tried putting a bp in the validate call back as @odhekar  put before, but it's strange that it's not reach on my end 
The constructor of `GoogleAdminStrategy` works normally 
However , when try putting a bp in function `validate` , nothing happen 
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/3c3f11e7-cecc-4abb-9736-ed62355a849a)
It seems that the authorization flow is failed at Google side  , the validate callback not work
Following is my setting on Google Console Cloud 
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/7a0e68af-dd15-42bc-a66b-80cd2c9d7784)

**Comment by adrien2p** [comment] 2023-07-09 16:29
Could you add the 7001 for the admin, i think the default is 7001

**Comment by odhekar** [comment] 2023-07-10 03:23
I am using these,

![image](https://github.com/adrien2p/medusa-plugins/assets/34801801/2c42e90c-e5cc-4882-980f-28b0781a92dd)

**Comment by nhatanhit** [comment] 2023-07-10 15:08
Thank @odhekar 
Just make sure that we are on the same page, did you get problem when accessing this URL : `http://localhost:9000/admin/auth/google`

Hi @adrien2p 
Mine still not working 
My admin local is http://localhost:7000 . Following is my medusa config 

`
// CORS when consuming Medusa from admin
const ADMIN_CORS = process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001,http://localhost:9000";
const BACKEND_URL = process.env.BACKEND_URL || "localhost:9000"
const ADMIN_URL = process.env.ADMIN_URL || "localhost:7000"
const STORE_URL = process.env.STORE_URL || "localhost:8000"
const plugins = [
   {
    resolve: "medusa-plugin-auth",
    options: {
        // strict: "all", // or "none" or "store" or "admin"
        google: {
            clientID: 'MY_GOOGLE_CLIENT_ID',
            clientSecret: 'MY_GOOGLE_CLIENT_SECRET',
 
            admin: {
                callbackUrl:`${BACKEND_URL}/admin/auth/google/cb`,
                failureRedirect: `${ADMIN_URL}/login`,
                successRedirect: `${ADMIN_URL}/`,
                authPath: '/admin/auth/google',
            }
            
        }
    }
  }
]

`

**Comment by adrien2p** [comment] 2023-07-11 07:32
Sorry guys i didnt get the bandwidth yet to investigate the missing google scopes. @odhekar if you put some breakpoint here and there during the bootstrap, is there a moment where the google scopes are present and then disappear?

**Comment by adrien2p** [comment] 2023-07-12 07:22
Good news, I ve been able to reproduce, I ve released a new version,can I get you to try please

**Comment by odhekar** [comment] 2023-07-12 07:53
I can confirm that 1.6.0 fixed the issue for me. :) thanks @adrien2p

**Comment by nhatanhit** [comment] 2023-07-12 08:40
Hi @adrien2p 
Mine still not working . The good news is I don't receive the "Unauthorized" message.

When entering the url "http://localhost:9000/admin/auth/google" , browser redirects me to Google Authorization Screen
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/a66a55be-e5ff-4e7a-b616-5924857f71ed)
It says that the request : `localhost:9000/admin/auth/google/cb` is invalid 
Then I tried pasting above URL into another tab of browser
It redirects me to this page 
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/8ef2f571-c782-4f33-ae0f-b240b3e6e727)

I updated the version of plugin : `medusa-plugin-auth` to version : 1.6.0 as well 

Please let me know anything that I can provide to help you investigate 
Thanks

**Comment by adrien2p** [comment] 2023-07-12 08:53
@nhatanhit looks like an issue with you.r google configuration, maybe in credentials?

**Comment by nhatanhit** [comment] 2023-07-12 13:57
Hi @adrien2p 
No , I don't think so
I tried creating new Express  project (not using medusa ) , and it's using Google OAuth Passport Library and same OAuth Credential as well , but my acc is verified successfully
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/b3aa6247-304b-46d5-a9a8-e3af0e718c35)

![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/61ba5f44-123d-42c7-adfb-5c23aee44154)
It's very strange .....

**Comment by adrien2p** [comment] 2023-07-12 15:39
have you added you user in the test users in the google cloud console for non published app?

**Comment by nhatanhit** [comment] 2023-07-12 16:39
yes @adrien2p 
I already added my google account as test user in the google cloud console. 
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/a58550f0-4f77-43cb-9f94-30049f5620ff)

The thing is : with one pair of  Google Client ID / Google Client secret ,  I able to login into my Express project  using my google  account but not for my medusa project.

**Comment by adrien2p** [comment] 2023-07-12 17:10
That sounds very strange, it works fo me and @odhekar so i don't understand the difference with you that makes that behaviour happening

**Comment by nhatanhit** [comment] 2023-07-13 02:10
@adrien2p 
Do you mind if you can upload your `medusa-config.js` with hiding all your credentials  ? I will do a check again 
Or can you create please small repository for demonstrating Google Authorization , I will check it out and run on my local machine ?

**Comment by adrien2p** [comment] 2023-07-18 07:58
here it is, I ve replaced the creds with '*'
```js
const ADMIN_CORS = `/http:\\/\\/*/`;
const STORE_CORS =
  "/http:\\/\\/*/";
const redisUrl = "redis://127.0.0.1:6379"
const DATABASE_URL="postgres://postgres@localhost:5432/medusa"

const plugins = [
  "medusa-fulfillment-manual",
  "medusa-payment-manual",
  {
    resolve: "@medusajs/admin",
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {
      autoRebuild: true,
    },
  },
  {
    resolve: "medusa-plugin-auth",
    /** @type {import('medusa-plugin-auth')} */
    options: {
      google: {

        clientID:
          "*",
        clientSecret: "*",
        admin: {
          callbackUrl: "http://localhost:9000/admin/auth/google/cb",

          failureRedirect: "http://localhost:7001/login",
          successRedirect: "http://localhost:7001/",

          authPath: "/admin/auth/google",
          authCallbackPath: "/admin/auth/google/cb",
        },
        store: {
          callbackUrl: "http://localhost:9000/store/auth/google/cb",

          failureRedirect: "http://localhost:8000/login",
          successRedirect: "http://localhost:8000/",

          authPath: "/store/auth/google",
          authCallbackPath: "/store/auth/google/cb",
        },
      },
      facebook: {
        clientID: "*",
        clientSecret: "*",
        admin: {
          callbackUrl: "http://localhost:9000/admin/auth/facebook/cb",

          failureRedirect: "http://localhost:7001/login",
          successRedirect: "http://localhost:7001/",

          authPath: "/admin/auth/facebook",
          authCallbackPath: "/admin/auth/facebook/cb",
        },
      },
    },
  },
];

module.exports = {
  plugins,
  projectConfig: {
    redis_url: redisUrl,
    admin_cors: ADMIN_CORS,
    store_cors: STORE_CORS,
    database_url: DATABASE_URL,
    database_type: "postgres",
    database_extra: {
      idle_in_transaction_session_timeout: 20000,
      idle_session_timeout: 20000,
      max: 20,
    },
    database_logging: false,
    jwt_secret: "test",
    cookie_secret: "test",
  },
  /*featureFlags: {
    tax_inclusive_pricing: true,
  },*/
  modules: {
    eventBus: {
      resolve: "@medusajs/event-bus-redis",
      options: {
        redisUrl
      }
    },
    cacheService: {
      resolve: "@medusajs/cache-redis",
      options: {
        redisUrl
      }
    },
  }
};

```

**Closed** 2023-08-01 01:56 UTC

**Comment by adrien2p** [comment] 2023-08-01 15:43
Can you share your finding @nhatanhit

**Comment by nhatanhit** [comment] 2023-08-06 14:00
Hi @adrien2p , sorry for replying late 

Unfortunately, It's still not working on my side. I went on doing the debug and think the Google Strategy which was initialized and linked to passport instance in loader function is not found when creating Google Auth routes, as you can see in following screens, Passport strategy only has session strategy. 

![medusa_passport_loader](https://github.com/adrien2p/medusa-plugins/assets/11988070/5a12ecd1-41a1-4e00-b4bd-1d3b4099b2fc)

I tried running a simple example on my local Express server, and see the Google Strategy is fully loaded when creating routes 

 
![google_stg_express](https://github.com/adrien2p/medusa-plugins/assets/11988070/4b3062ab-5ca8-46d6-9fb9-732f7c68ebd8)

It will take time to investigate this issue so I closed the issue. Besides, it seems that the issue only happens with my local computer 😄  

I am following this guideline : https://samippoudel.hashnode.dev/google-oauth-using-typescript-expressjs-passportjs-and-mongodb-ckvatnioy0hsu45s1db0r3qoy to implement the Google Auth for my backend server, it work with the route : **/admin/auth/google** , I can get my google  profile in the callback (line 40 in following screenshot) 

![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/26620ab8-0c2e-4eb5-8068-af83f7b96a18)

However , due to some unknown issue in underlying npm modules, my Google profile isn't serialized into the session ( I haven't figured out how to fix it )  . Plus I don't know to  call one services in the callback (line 30 in above screenshot )  to save the **profileObject** in the database. 

@adrien2p  if you know any pattern to resolve services in the callback, can you please suggest ? 

Thanks

**Comment by adrien2p** [comment] 2023-08-06 16:12
In general if it is not in the passport instance it means that the passport version in the plugin and the one in medusa does not match, it has to be the same version

**Comment by nhatanhit** [comment] 2023-08-08 16:11
@adrien2p 
Not sure that I understand your meaning, you mean MedusaJS already had an existing passport instance , and it's not compatible with passport version in your plugin ?

**Comment by adrien2p** [comment] 2023-08-08 16:15
Can you check in the node modules, if there is multiple passport installed between medusa and the plugins and the root. In theory, the plugin has the same version as medusa and i don't think medusa changed the passport version can you check

**Comment by nhatanhit** [comment] 2023-08-09 16:52
@adrien2p 
I tried with new fresh medusa 
After debugging, google strategy still not available in passport's strategies
![medusa_google_1](https://github.com/adrien2p/medusa-plugins/assets/11988070/4151d3c4-6af4-48a3-a75d-ec171d6441e3)

My package.json as you can see in following pic, there is no passport lib in the list of dependencies
![medusa_2_screenshot](https://github.com/adrien2p/medusa-plugins/assets/11988070/d6138d5a-e9da-4c6b-91a2-bec7c73b68d8)
Or you can find full list  in below link 
https://github.com/nhatanhit/fresh-medusa/blob/master/package.json

Is ^1.5.1 correct version for medusa plugin auth ?

**Comment by adrien2p** [comment] 2023-08-09 16:59
What i meant is that medusa is i stalling passport, and the plugin expect the same version as medusa, can you check if there is a passport package in node_modules/medusa-plugin-auth? I expect none of course

**Comment by adrien2p** [comment] 2023-08-09 17:03
I ve just checked and both medusa and the plugin target passport ^0.6.0 so in theory in your node module you should have only one passport package installed. Meaning that once everything is loaded including the plugin all the strategies should be in that passport instance

**Comment by adrien2p** [comment] 2023-08-09 17:06
Unfortunately if it was on my projet on my machine i could debug it very easily but i can't reproduce your issue and other users don't encounter it as well so i don't get why you have this behaviour, unless you are linking the package locally for your dev and debug and in that case you might have some dev deps installed

**Comment by nhatanhit** [comment] 2023-08-10 02:30
@adrien2p 
As your suggestion, I created public small repo : https://github.com/nhatanhit/fresh-medusa 
![image](https://github.com/adrien2p/medusa-plugins/assets/11988070/0e0c4266-b7c2-45a0-9ea0-ff41a84c000f)

I got similar issue in this repo as well, can you please check it out and run it when you have time ? 
If it runs successfully on your local machine,  I will do a check on all global node modules in my local machine.

**Comment by adrien2p** [comment] 2023-08-10 05:22
I look at it when i come back from vacation 😅 i am away for almost a month
